# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :VM1Vagrant do |vm1config|
    vm1config.vm.box = "ubuntu/trusty64"
    vm1config.vm.network :private_network, ip: "192.168.56.10"
    vm1config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
  config.vm.define :VM2Vagrant do |vm1config|
    vm1config.vm.box = "ubuntu/trusty64"
    vm1config.vm.network :private_network, ip: "192.168.56.11"
    vm1config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2024"]
   end
  end
end
